export type ApplicantField = {
  name: string;
  label: string;
  kind?: "text" | "tel" | "date" | "select" | "combo";
  options?: { value: string; label: string }[];
  suggestions?: string[];
  placeholder?: string;
  dateMode?: "past" | "future3m";
  hint?: string;
};

export const sportApplicantFields: ApplicantField[] = [
  { name: "last_name", label: "Прізвище", placeholder: "Куршацов" },
  { name: "first_name", label: "Ім'я", placeholder: "Андрій" },
  { name: "middle_name", label: "По батькові", placeholder: "Іванович" },
  { name: "birth_date", label: "Дата народження", kind: "date", dateMode: "past", placeholder: "дд.мм.рррр" },
  { name: "tax_id", label: "Ідентифікаційний код", placeholder: "10 цифр" },
  { name: "passport_number", label: "Номер паспорта", placeholder: "Серія та номер / ID-картка" },
  { name: "passport_issuer", label: "Ким виданий паспорт" },
  { name: "passport_date", label: "Коли виданий паспорт", kind: "date", dateMode: "past", placeholder: "дд.мм.рррр" },
  { name: "address", label: "Адреса проживання" },
  {
    name: "viber_phone",
    label: "Мобільний номер Viber (для посилання на оплату)",
    kind: "tel",
    placeholder: "+38 (0__) ___-__-__",
  },
];

export const carBrands = [
  "AUDI",
  "BMW",
  "CHERY",
  "CHEVROLET",
  "CITROEN",
  "DACIA",
  "DAEWOO",
  "FIAT",
  "FORD",
  "GEELY",
  "HONDA",
  "HYUNDAI",
  "INFINITI",
  "JEEP",
  "KIA",
  "LAND ROVER",
  "LEXUS",
  "MAZDA",
  "MERCEDES-BENZ",
  "MITSUBISHI",
  "NISSAN",
  "OPEL",
  "PEUGEOT",
  "PORSCHE",
  "RENAULT",
  "SEAT",
  "SKODA",
  "SSANGYONG",
  "SUBARU",
  "SUZUKI",
  "TESLA",
  "TOYOTA",
  "VOLKSWAGEN",
  "VOLVO",
  "ЗАЗ",
  "ВАЗ / LADA",
  "ГАЗ",
];

export const carModelSuggestions = [
  "ACCENT",
  "ASTRA",
  "CAMRY",
  "CIVIC",
  "COROLLA",
  "CR-V",
  "DUSTER",
  "FOCUS",
  "GOLF",
  "I30",
  "JETTA",
  "LANOS",
  "LEAF",
  "LOGAN",
  "MODEL 3",
  "MODEL Y",
  "OCTAVIA",
  "PASSAT",
  "QASHQAI",
  "RAV4",
  "SANDERO",
  "SPORTAGE",
  "TIGUAN",
  "TUCSON",
  "VITO",
  "X5",
];

export const greenCardApplicantFields: ApplicantField[] = [
  {
    name: "start_date",
    label: "Початок дії полісу",
    kind: "date",
    dateMode: "future3m",
    placeholder: "дд.мм.рррр",
    hint: "Від завтра і до 3 місяців наперед",
  },
  { name: "last_name", label: "Прізвище страхувальника (латиницею)", placeholder: "Kurshatsov" },
  { name: "first_name", label: "Ім'я страхувальника (латиницею)", placeholder: "Andrii" },
  { name: "middle_name", label: "По батькові (латиницею)", placeholder: "Ivanovych" },
  { name: "birth_date", label: "Дата народження", kind: "date", dateMode: "past", placeholder: "дд.мм.рррр" },
  { name: "tax_id", label: "ІПН страхувальника", placeholder: "10 цифр" },
  {
    name: "doc_type",
    label: "Документ, що посвідчує особу",
    kind: "select",
    options: [
      { value: "Посвідчення водія", label: "Посвідчення водія" },
      { value: "Паспорт громадянина України", label: "Паспорт громадянина України" },
      { value: "ID-паспорт громадянина України", label: "ID-паспорт громадянина України" },
      { value: "Закордонний паспорт", label: "Закордонний паспорт" },
    ],
  },
  { name: "doc_series", label: "Серія документа (латиницею)", placeholder: "BXI" },
  { name: "doc_number", label: "Номер документа", placeholder: "249475" },
  { name: "doc_issuer", label: "Ким виданий документ (латиницею)", placeholder: "TSC 3245" },
  { name: "doc_date", label: "Дата видачі документа", kind: "date", dateMode: "past", placeholder: "дд.мм.рррр" },
  { name: "region", label: "Область (латиницею)", placeholder: "Kyivska obl." },
  { name: "city", label: "Населений пункт (латиницею)", placeholder: "Kyiv" },
  { name: "street", label: "Вулиця (латиницею)", placeholder: "Heroiv Stalingrada Avenue" },
  { name: "house", label: "№ будинку", placeholder: "16/Б" },
  { name: "apartment", label: "№ квартири (за наявності)", placeholder: "69" },
  { name: "phone", label: "Телефон", kind: "tel", placeholder: "+38 (0__) ___-__-__" },
  {
    name: "viber_phone",
    label: "Мобільний номер Viber (для посилання на оплату)",
    kind: "tel",
    placeholder: "+38 (0__) ___-__-__",
  },
  { name: "plate", label: "Номерний знак", placeholder: "KA7885IP" },
  {
    name: "vehicle_type",
    label: "Тип транспортного засобу",
    kind: "select",
    options: [
      { value: "A - легкові до 8 місць", label: "A — Легкові пасажирські а/м до 8 місць" },
      { value: "A1 - мінібуси 9 місць", label: "A1 — Легкові пасажирські а/м 9 місць (мінібуси)" },
      {
        value: "A2 - вантажні до 3500 кг",
        label: "A2 — Мало/вантажні, вантажопасажирські до 3500 кг",
      },
      { value: "B - мотоцикли", label: "B — Мотоцикли та мотороллери" },
      { value: "C - вантажні", label: "C — Вантажні" },
      { value: "E - автобуси", label: "E — Автобуси" },
      { value: "F - причепи", label: "F — Причепи / напівпричепи" },
    ],
  },
  { name: "vin", label: "Номер кузова (VIN)", placeholder: "MALC741BBMM239991" },
  {
    name: "car_brand",
    label: "Марка авто (оберіть зі списку або впишіть вручну)",
    kind: "combo",
    suggestions: carBrands,
    placeholder: "HYUNDAI",
  },
  {
    name: "car_model",
    label: "Модель авто (оберіть зі списку або впишіть вручну)",
    kind: "combo",
    suggestions: carModelSuggestions,
    placeholder: "ACCENT",
  },
  { name: "car_year", label: "Рік випуску", placeholder: "2020" },
  { name: "seats", label: "К-сть місць, вкл. з водієм", placeholder: "5" },
  { name: "mass_total", label: "Повна маса, кг", placeholder: "1580" },
  { name: "mass_empty", label: "Маса без навантаження, кг", placeholder: "1160" },
  { name: "engine_volume", label: "Об'єм двигуна, куб. см", placeholder: "1368" },
  {
    name: "power_kw",
    label: "Потужність, кВт (для електромобілів)",
    placeholder: "Заповніть, якщо авто електричне",
    hint: "Для електромобілів об'єм двигуна не вказується — потрібна потужність у кВт.",
  },
];

export const autoDocTypes = [
  "Посвідчення водія",
  "Біометричний паспорт",
  "Паспорт",
  "Пенсійне посвідчення",
  "Учасник бойових дій",
];

export const autoApplicantFields: ApplicantField[] = [
  {
    name: "start_date",
    label: "Початок дії полісу",
    kind: "date",
    dateMode: "future3m",
    placeholder: "дд.мм.рррр",
    hint: "Від завтра і до 3 місяців наперед",
  },
  { name: "last_name", label: "Прізвище", placeholder: "ЛЮБЕНКО" },
  { name: "first_name", label: "Ім'я", placeholder: "АЛЕСЯ" },
  { name: "middle_name", label: "По батькові", placeholder: "ВОЛОДИМИРІВНА" },
  { name: "birth_date", label: "Дата народження", kind: "date", dateMode: "past", placeholder: "дд.мм.рррр" },
  { name: "tax_id", label: "ІПН", placeholder: "10 цифр" },
  { name: "address", label: "Адреса реєстрації", placeholder: "Харківська область, Харків, вул. Астрономічна, буд. 35Ж, кв. 100" },
  { name: "address_fact", label: "Фактична адреса (якщо відрізняється)", placeholder: "Заповніть, якщо відрізняється від адреси реєстрації" },
  { name: "phone", label: "Мобільний телефон", kind: "tel", placeholder: "+38 (0__) ___-__-__" },
  {
    name: "doc_type",
    label: "Тип документа",
    kind: "select",
    options: autoDocTypes.map((value) => ({ value, label: value })),
  },
  { name: "doc_number", label: "Номер документа", placeholder: "005907653" },
  { name: "doc_date", label: "Дата видачі", kind: "date", dateMode: "past", placeholder: "дд.мм.рррр" },
  { name: "doc_valid_until", label: "Дата кінця дії (за наявності)", kind: "date", placeholder: "дд.мм.рррр" },
  { name: "doc_issuer", label: "Ким виданий", placeholder: "Орган, що видав 6313" },
  {
    name: "car_brand",
    label: "Марка авто",
    kind: "combo",
    suggestions: carBrands,
    placeholder: "Mercedes-Benz",
  },
  {
    name: "car_model",
    label: "Модель авто",
    kind: "combo",
    suggestions: carModelSuggestions,
    placeholder: "212",
  },
  { name: "car_model_note", label: "Уточнення моделі (за наявності)", placeholder: "Наприклад: Long" },
  { name: "reg_country", label: "Країна реєстрації", placeholder: "Україна" },
  { name: "plate", label: "Державний реєстраційний номер", placeholder: "BC2530AI" },
  { name: "vin", label: "Номер кузова (VIN / шассі)", placeholder: "WDB9024611P822612" },
  { name: "car_year", label: "Рік випуску", placeholder: "2001" },
  { name: "engine_volume", label: "Об'єм двигуна, куб. см", placeholder: "2148" },
  { name: "car_color", label: "Колір", placeholder: "Сірий" },
  {
    name: "power_kw",
    label: "Потужність, кВт (для електромобілів)",
    placeholder: "Заповніть, якщо авто електричне",
    hint: "Для електромобілів об'єм двигуна не вказується — потрібна потужність у кВт.",
  },
  { name: "mass_total", label: "Повна маса, кг", placeholder: "1950" },
  { name: "mass_empty", label: "Маса без навантаження, кг", placeholder: "1463" },
  { name: "seats", label: "Кількість посадочних місць", placeholder: "5" },
];
