/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutostrahuvannyaRouteImport } from './routes/autostrahuvannya'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SportyvneStrahuvannyaRouteImport } from './routes/sportyvne-strahuvannya'
import { Route as TurystychneStrahuvannyaRouteImport } from './routes/turystychne-strahuvannya'
import { Route as ZelenaKartaRouteImport } from './routes/zelena-karta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogIndexRouteImport } from './routes/blog/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutostrahuvannyaRoute = AutostrahuvannyaRouteImport.update({
  id: '/autostrahuvannya',
  path: '/autostrahuvannya',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SportyvneStrahuvannyaRoute = SportyvneStrahuvannyaRouteImport.update({
  id: '/sportyvne-strahuvannya',
  path: '/sportyvne-strahuvannya',
  getParentRoute: () => rootRouteImport,
} as any)
const TurystychneStrahuvannyaRoute = TurystychneStrahuvannyaRouteImport.update({
  id: '/turystychne-strahuvannya',
  path: '/turystychne-strahuvannya',
  getParentRoute: () => rootRouteImport,
} as any)
const ZelenaKartaRoute = ZelenaKartaRouteImport.update({
  id: '/zelena-karta',
  path: '/zelena-karta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/autostrahuvannya': typeof AutostrahuvannyaRoute
  '/contacts': typeof ContactsRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sportyvne-strahuvannya': typeof SportyvneStrahuvannyaRoute
  '/turystychne-strahuvannya': typeof TurystychneStrahuvannyaRoute
  '/zelena-karta': typeof ZelenaKartaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/autostrahuvannya': typeof AutostrahuvannyaRoute
  '/contacts': typeof ContactsRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sportyvne-strahuvannya': typeof SportyvneStrahuvannyaRoute
  '/turystychne-strahuvannya': typeof TurystychneStrahuvannyaRoute
  '/zelena-karta': typeof ZelenaKartaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/autostrahuvannya': typeof AutostrahuvannyaRoute
  '/contacts': typeof ContactsRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sportyvne-strahuvannya': typeof SportyvneStrahuvannyaRoute
  '/turystychne-strahuvannya': typeof TurystychneStrahuvannyaRoute
  '/zelena-karta': typeof ZelenaKartaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/autostrahuvannya'
    | '/contacts'
    | '/offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/sportyvne-strahuvannya'
    | '/turystychne-strahuvannya'
    | '/zelena-karta'
    | '/admin'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/autostrahuvannya'
    | '/contacts'
    | '/offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/sportyvne-strahuvannya'
    | '/turystychne-strahuvannya'
    | '/zelena-karta'
    | '/admin'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/autostrahuvannya'
    | '/contacts'
    | '/offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/sportyvne-strahuvannya'
    | '/turystychne-strahuvannya'
    | '/zelena-karta'
    | '/_authenticated/admin'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AutostrahuvannyaRoute: typeof AutostrahuvannyaRoute
  ContactsRoute: typeof ContactsRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportyvneStrahuvannyaRoute: typeof SportyvneStrahuvannyaRoute
  TurystychneStrahuvannyaRoute: typeof TurystychneStrahuvannyaRoute
  ZelenaKartaRoute: typeof ZelenaKartaRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autostrahuvannya': {
      id: '/autostrahuvannya'
      path: '/autostrahuvannya'
      fullPath: '/autostrahuvannya'
      preLoaderRoute: typeof AutostrahuvannyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportyvne-strahuvannya': {
      id: '/sportyvne-strahuvannya'
      path: '/sportyvne-strahuvannya'
      fullPath: '/sportyvne-strahuvannya'
      preLoaderRoute: typeof SportyvneStrahuvannyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turystychne-strahuvannya': {
      id: '/turystychne-strahuvannya'
      path: '/turystychne-strahuvannya'
      fullPath: '/turystychne-strahuvannya'
      preLoaderRoute: typeof TurystychneStrahuvannyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zelena-karta': {
      id: '/zelena-karta'
      path: '/zelena-karta'
      fullPath: '/zelena-karta'
      preLoaderRoute: typeof ZelenaKartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AutostrahuvannyaRoute: AutostrahuvannyaRoute,
  ContactsRoute: ContactsRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportyvneStrahuvannyaRoute: SportyvneStrahuvannyaRoute,
  TurystychneStrahuvannyaRoute: TurystychneStrahuvannyaRoute,
  ZelenaKartaRoute: ZelenaKartaRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
